### ISSUE TITLE
NoScript support

### ISSUE THREAD

**Issue by luphoria** [titaniumnetwork-dev/Oxide#3]
this website should not be locked to only JavaScript users - there's no reason for it to be. (it also prevents scrapers)

**Comment by QuiteAFancyEmerald** [comment]
Why? Most modern web browsers or users have JS available or enabled.... a good portion of modern websites use this setup. The only reason why React is used is simply because of organization and ease.

**Comment by e9x** [comment]
Fixed in 4529417b2025d703ecc793f6bf874ed7d6cd3db7. This project now uses Next.js with SSR.
